### ISSUE TITLE
Parsing fails when there is a newline in ENV

### ISSUE THREAD

**Issue by moshen** [lukasmartinelli/hadolint#7]
```
FROM debian:stable
MAINTAINER Foo <foo@foo>

ENV TEST=1 \
  TEST2=2
```

Fails with:
```
"<string>" (line 4, column 13):
unexpected "\n"
```

```
FROM debian:stable
MAINTAINER Foo <foo@foo>

ENV TEST=1 TEST2=2
```

Works.

**Comment by lukasmartinelli** [comment]
You got me :)
There are alot of Dockerfile parsing gotchas I still have to find and fix.

I have an integration test that lints some hundred Dockerfiles to check whether the parser fails.

https://github.com/lukasmartinelli/hadolint/blob/master/integration_test.sh

**Comment by moshen** [comment]
I imagine the Dockerfile syntax has a few rough edges.  Thank you for this, it's a great piece of software :beers: .  I'm hoping to integrate this into my Docker workflows.

**Comment by AndyBerman** [comment]
I know there's a workaround to put all the variables on one line, but when there are many variables, it becomes difficult to read.  Here's an example of what we have:

ENV LD_LIBRARY_PATH="/usr/lib/oracle/11.2/client64/lib" ORACLE_HOME="/usr/lib/oracle/11.2/client64" PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/oracle/11.2/client64/bin" APACHE_RUN_USER="www-data" APACHE_RUN_GROUP="www-data" APACHE_LOG_DIR="/var/log/httpd"

We'd prefer not to break them out into multiple lines in order to reduce the number of layers.

Hadolint is awesome, but this one issue is preventing us from using it.

**Comment by sweetclimusic** [comment]
I have looked at all the closed issues relating to this e.g. issue( #33, #27).  However I have experienced this error using the latest docker image

( powershell ) Get-Content .\Dockerfile | docker run --rm -i lukasmartinelli/hadolint:latest
Note. Windows powershell < is not allowed so you have to get the file contents and | pipe to the docker command. might want to add that in the readme on how to use hadolint for docker.

error:

> /dev/stdin:6:1 unexpected '&' expecting space, "\t", "ONBUILD", "FROM", "COPY", "RUN", "WORKDIR", "ENTRYPOINT", "VOLUME", "EXPOSE", "ENV", "ARG", "USER", "LABEL", "STOPSIGNA
> L", "CMD", "SHELL", "MAINTAINER", "ADD", "#", "HEALTHCHECK" or end of input

dockerfile sample

```
FROM php:5-apache
LABEL description="Containerized development of on local machines using docker"
COPY docker-config/php.ini /usr/local/etc/php/
#enable php modules (modules that have no prerequisites )
RUN docker-php-ext-install mysql mysqli pdo_mysql bcmath \
&& docker-php-ext-enable mysql mysqli pdo_mysql bcmath
#install zlib
RUN apt-get update \
&& apt-get -y install zlib1g-dev \
&& apt-get clean \
&& rm -r /var/lib/apt/lists/* \
&& docker-php-ext-configure zlib --with-zlib=/dir \
&& docker-php-ext-install zlib \
&& docker-php-ext-enable zlib

EXPOSE 80

CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
```
